server:
  port: 8080

documentation:
  swagger:
    services:
      -
        name: Service1
        url: http://localhost:8081/v1/api-docs
        version: 1.0


spring:
  security:
    user:
      name: admin
      password: 123

springdoc:
  swagger-ui:
    enabled: true
    use-root-path: true
  api-docs:
    path: /v1/api-docs